import Head from "next/head";
import axios from "axios";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar/Navbar";
import Footer from "../components/Footer";
import Welcome from "../components/Home/index.js";
import TraerCanchas from "../components/TraerCanchas/TraerCanchas";
import Ubicacion from "./Ubicacion";

export default function Home() {
  const canchas = [{ nombre: "5 vs 5", info: "alguna info", id: 1 },{ nombre: "7 vs 7", info: "alguna info", id: 2 },{ nombre: "11 vs 11", info: "alguna info", id: 3 }];
  return (
    <div className={styles.body}>
      <Head>
        <title>Canchas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Welcome />
      <TraerCanchas canchas={canchas} />
      <Ubicacion/>

      <Footer />
    </div>
  );
}
